Importing data

In [6]:
import pandas as pd
import numpy as np

spotify = pd.read_csv("C:\\Users\\damur\\Desktop\\Turing\\Python\\spotifytoptracks.csv", index_col=0)

print('Setup Is complete')

Setup Is complete

Information about data

In [2]:
spotify.info()
spotify.describe()
spotify.head()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   artist            50 non-null     object
 1   album             50 non-null     object
 2   track_name        50 non-null     object
 3   track_id          50 non-null     object
 4   energy            50 non-null     float64
 5   danceability      50 non-null     float64
 6   key               50 non-null     int64
 7   loudness          50 non-null     float64
 8   acousticness      50 non-null     float64
 9   speechiness       50 non-null     float64
 10  instrumentalness  50 non-null     float64
 11  liveness          50 non-null     float64
 12  valence           50 non-null     float64
 13  tempo             50 non-null     float64
 14  duration_ms       50 non-null     int64
 15  genre             50 non-null     object
dtypes: float64(9), int64(2), object(5)
memory usage: 6.6+ KB

,artist,album,track_name,track_id,energy,danceability,key,loudness,acousticness,speechiness,instrumentalness,liveness,valence,tempo,duration_ms,genre
0,The Weeknd,After Hours,Blinding Lights,0VjIjW4GlUZAMYd2vXMi3b,0.730,0.514,1,-5.934,0.00146,0.0598,0.000095,0.0897,0.334,171.005,200040,R&B/Soul
1,Tones And I,Dance Monkey,Dance Monkey,1rgnBhdG2JDFTbYkYRZAku,0.593,0.825,6,-6.401,0.68800,0.0988,0.000161,0.1700,0.540,98.078,209755,Alternative/Indie
2,Roddy Ricch,Please Excuse Me For Being Antisocial,The Box,0nbXyq5TXYPCO7pr3N8S4I,0.586,0.896,10,-6.687,0.10400,0.0559,0.000000,0.7900,0.642,116.971,196653,Hip-Hop/Rap
3,SAINt JHN,Roses (Imanbek Remix),Roses - Imanbek Remix,2Wo6QQD1KMDWeFkkjLqwx5,0.721,0.785,8,-5.457,0.01490,0.0506,0.004320,0.2850,0.894,121.962,176219,Dance/Electronic
4,Dua Lipa,Future Nostalgia,Don't Start Now,3PfIrDoz19wz7qK7tYeu62,0.793,0.793,11,-4.521,0.01230,0.0830,0.000000,0.0951,0.679,123.950,183290,Nu-disco

Drop the duplicates

In [5]:
spotify = spotify.drop_duplicates()

Treating outliers.

In [7]:
numeric_cols = spotify.select_dtypes(include=['float64', 'int64']).columns

Q1 = spotify['duration_ms'].quantile(0.25)
Q3 = spotify['duration_ms'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = spotify[(spotify['duration_ms'] < lower) | (spotify['duration_ms'] > upper)]

for col in numeric_cols:
    Q1 = spotify[col].quantile(0.25)
    Q3 = spotify[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = spotify[(spotify[col] < lower) | (spotify[col] > upper)]

    print(f"Column: {col}, Outliers found: {len(outliers)}")

Column: energy, Outliers found: 0
Column: danceability, Outliers found: 3
Column: key, Outliers found: 0
Column: loudness, Outliers found: 1
Column: acousticness, Outliers found: 7
Column: speechiness, Outliers found: 6
Column: instrumentalness, Outliers found: 12
Column: liveness, Outliers found: 3
Column: valence, Outliers found: 0
Column: tempo, Outliers found: 0
Column: duration_ms, Outliers found: 2

How many observations are there in this dataset?
How many features does this dataset have?

In [8]:
spotify.shape

(50, 16)

Which of the features are categorical?

In [9]:
spotify.select_dtypes(include=['object']).columns

Index(['artist', 'album', 'track_name', 'track_id', 'genre'], dtype='object')

Which of the features are numeric?

In [10]:
spotify.select_dtypes(include=['int64','float64']).columns

Index(['energy', 'danceability', 'key', 'loudness', 'acousticness',
       'speechiness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms'],
      dtype='object')

Are there any artists that have more than 1 popular track? If yes, which, and how many?

In [14]:
artists = spotify.groupby('artist')
artists.size().loc[lambda x: x > 1]

artist
Billie Eilish    3
Dua Lipa         3
Harry Styles     2
Justin Bieber    2
Lewis Capaldi    2
Post Malone      2
Travis Scott     3
dtype: int64

Who was the most popular artist?

In [15]:
artists.size().idxmax()
#billie has 3 songs as many of artists but why she is ranked first?

'Billie Eilish'

How many artists have their songs in the top 50 in total?

In [ ]:
spotify.artist.nunique()
#can use len(artists) also, but chatgpt said it is not clear method

40

Are there any albums that have more than 1 popular track? If yes, which, and how many?

In [19]:
albums = spotify.groupby('album')
albums.size().loc[lambda x: x > 1]

album
Changes                 2
Fine Line               2
Future Nostalgia        3
Hollywood's Bleeding    2
dtype: int64

How many albums in total have their songs in the top 50?

In [20]:
spotify.album.nunique()

45

Which tracks have a danceability score above 0.7?

In [24]:
spotify['track_name'][spotify['danceability'] > 0.7]

1                                      Dance Monkey
2                                           The Box
3                             Roses - Imanbek Remix
4                                   Don't Start Now
5                      ROCKSTAR (feat. Roddy Ricch)
7                  death bed (coffee for your head)
8                                           Falling
10                                             Tusa
13                                  Blueberry Faygo
14                         Intentions (feat. Quavo)
15                                     Toosie Slide
17                                           Say So
18                                         Memories
19                       Life Is Good (feat. Drake)
20                 Savage Love (Laxed - Siren Beat)
22                                      Breaking Me
24                              everything i wanted
25                                         Señorita
26                                          bad guy
27                  WAP (feat. Megan Thee Stallion)
28                                      Sunday Best
29                      Godzilla (feat. Juice WRLD)
31                                   Break My Heart
32                                         Dynamite
33                 Supalonely (feat. Gus Dapperton)
37    Sunflower - Spider-Man: Into the Spider-Verse
38                                            Hawái
39                                          Ride It
40                                       goosebumps
41                        RITMO (Bad Boys For Life)
42                                       THE SCOTTS
49                                       SICKO MODE
Name: track_name, dtype: object

Which tracks have a danceability score below 0.4?

In [ ]:
spotify['track_name'][(spotify['danceability'] < 0.7) & (spotify['danceability'] > 0.4)]
#you can use .between also

0                                    Blinding Lights
6                                   Watermelon Sugar
9                                  Someone You Loved
11                                           ROXANNE
12                                           Circles
16                                     Before You Go
21                                         Adore You
30                                             Yummy
34              ily (i love you baby) (feat. Emilee)
35                   Rain On Me (with Ariana Grande)
36                               HIGHEST IN THE ROOM
43                                           Safaera
45                                      Lucid Dreams
46                 Stuck with U (with Justin Bieber)
47    If the World Was Ending - feat. Julia Michaels
48                                          Physical
Name: track_name, dtype: object

Which tracks have their loudness above -5?

In [27]:
spotify['track_name'][spotify['loudness'] > -5]

4                                   Don't Start Now
6                                  Watermelon Sugar
10                                             Tusa
12                                          Circles
16                                    Before You Go
17                                           Say So
21                                        Adore You
23                           Mood (feat. iann dior)
31                                   Break My Heart
32                                         Dynamite
33                 Supalonely (feat. Gus Dapperton)
35                  Rain On Me (with Ariana Grande)
37    Sunflower - Spider-Man: Into the Spider-Verse
38                                            Hawái
39                                          Ride It
40                                       goosebumps
43                                          Safaera
48                                         Physical
49                                       SICKO MODE
Name: track_name, dtype: object

Which tracks have their loudness below -8?

In [28]:
spotify['track_name'][spotify['loudness'] < -5]

0                                    Blinding Lights
1                                       Dance Monkey
2                                            The Box
3                              Roses - Imanbek Remix
5                       ROCKSTAR (feat. Roddy Ricch)
7                   death bed (coffee for your head)
8                                            Falling
9                                  Someone You Loved
11                                           ROXANNE
13                                   Blueberry Faygo
14                          Intentions (feat. Quavo)
15                                      Toosie Slide
18                                          Memories
19                        Life Is Good (feat. Drake)
20                  Savage Love (Laxed - Siren Beat)
22                                       Breaking Me
24                               everything i wanted
25                                          Señorita
26                                           bad guy
27                   WAP (feat. Megan Thee Stallion)
28                                       Sunday Best
29                       Godzilla (feat. Juice WRLD)
30                                             Yummy
34              ily (i love you baby) (feat. Emilee)
36                               HIGHEST IN THE ROOM
41                         RITMO (Bad Boys For Life)
42                                        THE SCOTTS
44                              lovely (with Khalid)
45                                      Lucid Dreams
46                 Stuck with U (with Justin Bieber)
47    If the World Was Ending - feat. Julia Michaels
Name: track_name, dtype: object

Which track is the longest?

In [ ]:
spotify['track_name'][spotify['duration_ms'].idxmax()]
#entire row spotify.loc[spotify['duration_ms'].idxmax()]

'SICKO MODE'

Which track is the shortest?

In [31]:
spotify['track_name'][spotify['duration_ms'].idxmin()]

'Mood (feat. iann dior)'

Which genre is the most popular?

In [ ]:
spotify['genre'].value_counts().head(1)
#if u will use idxmax it will output only name

genre
Pop    14
Name: count, dtype: int64

Which genres have just one song in the top 50?

In [ ]:
spotify.groupby('genre').size().loc[lambda x: x == 1]
#can use spotify['genre'].value_counts()[spotify['genre'].value_counts() == 1]  also

genre
Alternative/reggaeton/experimental    1
Chamber pop                           1
Dance-pop/Disco                       1
Disco-pop                             1
Dreampop/Hip-Hop/R&B                  1
Hip-Hop/Trap                          1
Nu-disco                              1
Pop rap                               1
Pop/Soft Rock                         1
R&B/Hip-Hop alternative               1
dtype: int64

How many genres in total are represented in the top 50?

In [39]:
spotify.genre.nunique()

16

Which features are strongly positively correlated?

In [47]:
corr = spotify.corr(numeric_only=True) #find all columns with numbers
corr_unstacked = corr.unstack() # to turn matrix into a long list of pairs
strong_pos = corr_unstacked[(corr_unstacked > 0.5) & (corr_unstacked < 1)] #if not 1 then it would show pairs like energy energy, loudness loudness
strong_pos.sort_values()

energy    loudness    0.79164
loudness  energy      0.79164
dtype: float64

Which features are strongly negatively correlated?

In [ ]:
weak_pos = corr_unstacked[(corr_unstacked < -0.5)] 
weak_pos.sort_values()

energy            acousticness       -0.682479
acousticness      energy             -0.682479
loudness          instrumentalness   -0.553735
instrumentalness  loudness           -0.553735
dtype: float64

Which features are not correlated?

In [53]:
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
clean_corr = upper.unstack().dropna()

weak_pos = clean_corr[(corr_unstacked < 0.1) & (corr_unstacked > -0.1)]
weak_pos

key               energy              0.062428
loudness          key                -0.009178
speechiness       energy              0.074267
                  key                -0.094965
                  loudness           -0.021693
instrumentalness  danceability       -0.017706
                  key                 0.020802
                  speechiness         0.028948
liveness          energy              0.069487
                  danceability       -0.006648
                  loudness           -0.069939
                  instrumentalness   -0.087034
valence           speechiness         0.053867
                  liveness           -0.033366
tempo             energy              0.075191
                  key                 0.080475
                  instrumentalness    0.018853
                  liveness            0.025457
                  valence             0.045089
duration_ms       energy              0.081971
                  danceability       -0.033763
                  key                -0.003345
                  loudness            0.064130
                  acousticness       -0.010988
                  liveness           -0.090188
                  valence            -0.039794
dtype: float64

How does the danceability score compare between Pop, Hip-Hop/Rap, Dance/Electronic, and Alternative/Indie genres?

In [55]:
genres = ['Pop', 'Hip-Hop/Rap', 'Dance/Electronic', 'Alternative/Indie']
spotify[spotify['genre'].isin(genres)].groupby('genre').agg(mean_danceability=('danceability', 'mean'))

                   mean_danceability
genre
Alternative/Indie           0.661750
Dance/Electronic            0.755000
Hip-Hop/Rap                 0.765538
Pop                         0.677571

How does the loudness score compare between Pop, Hip-Hop/Rap, Dance/Electronic, and Alternative/Indie genres?

In [57]:
genres = ['Pop', 'Hip-Hop/Rap', 'Dance/Electronic', 'Alternative/Indie']
spotify[spotify['genre'].isin(genres)].groupby('genre').agg(mean_loudness =('loudness', 'mean'))

                   mean_loudness
genre
Alternative/Indie      -5.421000
Dance/Electronic       -5.338000
Hip-Hop/Rap            -6.917846
Pop                    -6.460357

How does the acoustics score compare between Pop, Hip-Hop/Rap, Dance/Electronic, and Alternative/Indie genres?

In [59]:
genres = ['Pop', 'Hip-Hop/Rap', 'Dance/Electronic', 'Alternative/Indie']
spotify[spotify['genre'].isin(genres)].groupby('genre').agg(mean_loudness =('acousticness', 'mean'))

                   mean_loudness
genre
Alternative/Indie       0.583500
Dance/Electronic        0.099440
Hip-Hop/Rap             0.188741
Pop                     0.323843